### ISSUE TITLE
upgrading firmtool

### ISSUE THREAD

**Issue by urherenow** [TuxSH/firmtool#2]
I've run "pip install -U git+https://github.com/TuxSH/firmtool.git" under both Python27 and under Python36. With either, running "firmtool -v" returns Firmtool 1.2... even though the latest release is 1.3. I know there is no interference from another firmtool because manually deleting it from the python directory results in a file not found error. Rinse and repeat.

**Comment by Derek1199** [comment]
Check all your python directories for something like a firmtool script. Remove all those. Also try upgrading cryptography again before doing this. Then reinstall firmtool again.

**Comment by urherenow** [comment]
The -U flag already upgrades cryptography (whether it needs an upgrade or not). Do you see "Firmtool 1.3" when you run firmtool -v? I'm seeing the same behavior on ubuntu bash as well as Windows cmd. And in case you're wondering, making bash oblivious to my Windows path was one of the first things I did. There are no conflicts in that respect.

**Comment by fincs** [comment]
TuxSH forgot to bump the [version number](https://github.com/TuxSH/firmtool/blob/master/firmtool/__main__.py#L6).

**Comment by urherenow** [comment]
This has been resolved (probably for years now, lol). On ubuntu, I found it best to install with 
sudo -HE pip  install git+https://github.com/TuxSH/firmtool.git
and if you have both python 2.x and 3.x, also
sudo -HE pip3  install git+https://github.com/TuxSH/firmtool.git

for good measure.
